# Pre-commit configuration
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - "--max-line-length=88"
          - "--extend-ignore=E203,E501,E402,F403,F405,F401,E231,E272,E702,E202,E201,E221"
          - "--exclude=tests/e2e/"

  # ruff disabled temporarily due to config conflicts
  # - repo: https://github.com/charliermarsh/ruff-pre-commit
  #   rev: v0.0.287
  #   hooks:
  #     - id: ruff
  #       args: ["--fix", "--exit-non-zero-on-fix"]

  - repo: local
    hooks:
      - id: pytest-quick
        name: pytest-quick
        entry: uv run pytest tests/unit/ tests/integration/ -x --tb=line --disable-warnings -q
        language: system
        pass_filenames: false
        always_run: false
