# Simple Docker Compose for development (SQLite)

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=django_project.totonoe_template.settings.dev
    command: >
      sh -c "uv run python manage.py migrate &&
             uv run python manage.py collectstatic --noinput &&
             uv run uvicorn main_asgi:app --host 0.0.0.0 --port 8000 --reload"
